version: 2
jobs:
  build:
    docker:
      - image: joyzoursky/python-chromedriver:2.7-selenium
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: python heli.py
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report
